bot:
  name: t_bot
  username: t_bot
  token: 4666879:Asdfgdfgs6574sdfg6+75sdfg5
  api_id: 1111111
  api_hash: adsas34534rer34534wer
  admin: 1012736210
database:
  login: qqqqqqqq@gmail.com
  password: kkjhkg
contacts:
  common_chanel: hghjfgh
  admin_chanel: fgjghfg
  admin_chanel_id: -10015165464
