bot:  
  admin_id: 101
  name: t_bot
  username: t_bot
  token: 4666879:Asdfgdfgs6574sdfg6+75sdfg5
database:
  cred_file: gsheetscred.json
  table_id: cYbPQrmmVQ9QjhaNUJcALQ
  g_drive_media_folder: c8oIPLZnbj_0vKX7o
contacts:
  common_chanel: hghjfgh
  admin_chanel: fgjghfg
  admin_chanel_id: -10015165464
